version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every week on monday
    schedule:
      interval: "weekly"
    reviewers:
      - "julienw"
      - "canova"
      - "gregtatum"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    reviewers:
      - "julienw"
      - "canova"
      - "gregtatum"
    ignore:
      - dependency-name: "node"
        versions: [">12"]
